package uk.gov.dcsf._20090308;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-08-24T14:48:11.710+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.dcsf.gov.uk/20090308/", name = "OnlineQueryService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, uk.gov.dcsf._20090810.ObjectFactory.class})
public interface OnlineQueryService {

    @WebMethod(operationName = "FetchBatchStatus", action = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/FetchBatchStatus")
    @Action(input = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/FetchBatchStatus", output = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/FetchBatchStatusResponse")
    @RequestWrapper(localName = "FetchBatchStatus", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.FetchBatchStatus")
    @ResponseWrapper(localName = "FetchBatchStatusResponse", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.FetchBatchStatusResponse")
    @WebResult(name = "FetchBatchStatusResult", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
    public uk.gov.dcsf._20090810.FetchBatchStatusResponseStructure fetchBatchStatus(
            @WebParam(name = "requestInput", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
                    uk.gov.dcsf._20090810.FetchBatchStatusRequestStructure requestInput
    );

    @WebMethod(operationName = "SubmitBatchQuery", action = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitBatchQuery")
    @Action(input = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitBatchQuery", output = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitBatchQueryResponse")
    @RequestWrapper(localName = "SubmitBatchQuery", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.SubmitBatchQuery")
    @ResponseWrapper(localName = "SubmitBatchQueryResponse", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.SubmitBatchQueryResponse")
    @WebResult(name = "SubmitBatchQueryResult", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
    public uk.gov.dcsf._20090810.SubmitBatchQueryResponseStructure submitBatchQuery(
            @WebParam(name = "requestInput", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
                    uk.gov.dcsf._20090810.SubmitBatchQueryRequestStructure requestInput
    );

    @WebMethod(operationName = "SubmitDeleteBatch", action = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitDeleteBatch")
    @Action(input = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitDeleteBatch", output = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitDeleteBatchResponse")
    @RequestWrapper(localName = "SubmitDeleteBatch", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.SubmitDeleteBatch")
    @ResponseWrapper(localName = "SubmitDeleteBatchResponse", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.SubmitDeleteBatchResponse")
    @WebResult(name = "SubmitDeleteBatchResult", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
    public uk.gov.dcsf._20090308.SubmitDeleteBatchResponseStructure submitDeleteBatch(
            @WebParam(name = "requestInput", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
                    uk.gov.dcsf._20090308.SubmitDeleteBatchRequestStructure requestInput
    );

    @WebMethod(operationName = "GetFSMSystemStatus", action = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/GetFSMSystemStatus")
    @Action(input = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/GetFSMSystemStatus", output = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/GetFSMSystemStatusResponse")
    @RequestWrapper(localName = "GetFSMSystemStatus", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.GetFSMSystemStatus")
    @ResponseWrapper(localName = "GetFSMSystemStatusResponse", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.GetFSMSystemStatusResponse")
    @WebResult(name = "GetFSMSystemStatusResult", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
    public uk.gov.dcsf._20090308.SystemStatusResponse getFSMSystemStatus(
            @WebParam(name = "details", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
                    uk.gov.dcsf._20090308.SystemStatusWithAuthenticationRequest details
    );

    @WebMethod(operationName = "SubmitSingleQuery", action = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitSingleQuery")
    @Action(input = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitSingleQuery", output = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/SubmitSingleQueryResponse")
    @RequestWrapper(localName = "SubmitSingleQuery", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.SubmitSingleQuery")
    @ResponseWrapper(localName = "SubmitSingleQueryResponse", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.SubmitSingleQueryResponse")
    @WebResult(name = "SubmitSingleQueryResult", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
    public uk.gov.dcsf._20090308.SubmitSingleQueryResult submitSingleQuery(
            @WebParam(name = "requestInput", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
                    uk.gov.dcsf._20090308.SubmitSingleQueryRequest requestInput
    );

    @WebMethod(operationName = "FetchBatchResults", action = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/FetchBatchResults")
    @Action(input = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/FetchBatchResults", output = "http://www.dcsf.gov.uk/20090308/OnlineQueryService/FetchBatchResultsResponse")
    @RequestWrapper(localName = "FetchBatchResults", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.FetchBatchResults")
    @ResponseWrapper(localName = "FetchBatchResultsResponse", targetNamespace = "http://www.dcsf.gov.uk/20090308/", className = "uk.gov.dcsf._20090308.FetchBatchResultsResponse")
    @WebResult(name = "FetchBatchResultsResult", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
    public uk.gov.dcsf._20090810.FetchBatchResultsResponseStructure fetchBatchResults(
            @WebParam(name = "requestInput", targetNamespace = "http://www.dcsf.gov.uk/20090308/")
                    uk.gov.dcsf._20090810.FetchBatchResultsRequestStructure requestInput
    );
}
