package uk.gov.dcsf._20090308;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-08-24T14:48:11.776+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "OnlineQueryService", 
                  wsdlLocation = "file:/C:/Users/daniel.rothig/ecs-loadtest/src/main/wsdl/OnlineQueryService_1.wsdl",
                  targetNamespace = "http://www.dcsf.gov.uk/20090308/") 
public class OnlineQueryService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.dcsf.gov.uk/20090308/", "OnlineQueryService");
    public final static QName Main = new QName("http://www.dcsf.gov.uk/20090308/", "Main");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/daniel.rothig/ecs-loadtest/src/main/wsdl/OnlineQueryService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnlineQueryService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/daniel.rothig/ecs-loadtest/src/main/wsdl/OnlineQueryService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnlineQueryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnlineQueryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlineQueryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OnlineQueryService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OnlineQueryService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OnlineQueryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OnlineQueryService
     */
    @WebEndpoint(name = "Main")
    public OnlineQueryService getMain() {
        return super.getPort(Main, OnlineQueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineQueryService
     */
    @WebEndpoint(name = "Main")
    public OnlineQueryService getMain(WebServiceFeature... features) {
        return super.getPort(Main, OnlineQueryService.class, features);
    }

}
